export enum ApiPathsEnum {
  API_PREFIX = '',
  ADMIN_PREFIX = '/admin',
  LOGIN = '/login',
  REGISTER = '/register',
  ITEM = '/item',
  ADMIN_ITEM = ADMIN_PREFIX + '/item',
  SAVED = '/saved',
  ITEM_BY_NAME = '/item-by-name',
  ITEMS_BY_CATEGORY = '/items-by-category',
  CART = '/cart',
  ORDER = '/order',
  ADMIN_ORDER = ADMIN_PREFIX + '/order',
  ADMIN_REGISTER = ADMIN_PREFIX + '/register',
  PROFILE_INFO = '/profile',
  TOKEN = '/token',
  REFRESH = '/refresh',
  CATEGORY = '/category',
  CATEGORY_UPPER = '/category-upper',
  SUBCATEGORY = '/subcategory',
  ADMIN_CATEGORY = ADMIN_PREFIX + '/category',
  ADMIN_SUBCATEGORY = ADMIN_PREFIX + '/subcategory',
}
